### ISSUE TITLE
[Epic] Document `cryostat-agent`

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostatio.github.io#90]
- [ ] [Story] Document general description + purpose
- [ ] [Story] Document common suggested use cases + configuration options required
- [ ] [Story] Document all configuration options
